### ISSUE TITLE
Error in contDeam: Unable to convert string="-nan"

### ISSUE THREAD

**Issue by fherelias** [grenaud/schmutzi#31]
Hello, I am encountering an error while running the contDeam.pl script. The error message reads as follows:

Libgab.cpp: destringify() Unable to convert string="-nan"
system  cmd /opt/schmutzi/src/contDeam  -deamread -deam5p outputdir/Sample12.endo.5p.prof  -deam3p outputdir/Sample12.endo.3p.prof  -log  outputdir/Sample12.cont.deam  -r human_rCRS.fasta   Sample12.mt.bam failed: 256 at /opt/schmutzi/src/contDeam.pl line 22.

This occurs when running the following commands:
running cmd /opt/schmutzi/src/bam2prof -length  2 -endo -double -5p outputdir/Sample12.endo.5p.prof  -3p outputdir/Sample12.endo.3p.prof Sample12.mt.bam
running cmd /opt/schmutzi/src/contDeam  -deamread -deam5p outputdir/Sample12.endo.5p.prof  -deam3p outputdir/Sample12.endo.3p.prof  -log  outputdir/Sample12.cont.deam  -r human_rCRS.fasta   Sample12.mt.bam

Could you provide any guidance on what might be causing this issue, or any suggestions on resolving it?

Thank you for your help.

**Comment by grenaud** [comment]
Thank you for your interest! Please check the readme  and the section "I run contDeam.pl on my BAM file and get nan errors:

"

**Comment by Weakne55** [comment]
I accidentally discovered that the success of contDeam.pl is affected by the collapse of reads. On some of my data, without collapsing raw reads before alignment to the genome, the script crashed with the -NaN error. What could be the reason for such strange behavior?

**Comment by grenaud** [comment]
This is not strange this is very expected behavior :-) 

trimmed and/or merged reads become essentially "single-end". If you leave paired-end reads unmerged for aDNA, they will be left as pairs and be overlooked by contDeam.pl. Only "single-end" are considered. so nan means that you are dividing by zero because you have no observations.

However I do not recommend this workflow as essentially you have 2 observations but it is the same DNA molecule. But in reality you don't have 2x coverage but 1X but as 2 observations.
